---
- name: remove items from dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: "{{ dock.remove }}"

- name: add items to dock
  shell: dockutil --find "{{ item.name }}" || dockutil --add "{{ item.path }}"
  with_items: "{{ dock.persist }}"

- name: assign order to dock items
  shell: dockutil --move "{{ item.name }}" --position "{{ item.pos }}"
  with_items: "{{ dock.persist }}"
